### ISSUE TITLE
what to do on 5/11

### ISSUE THREAD

**Issue by pzzd** [apzzd/ProjectCSGirls-2023#10]
- [x] start new recording in the morning with box, sound files will already by in pieces
- [x] run clips through ML model to classify sounds
- [x] listen to a few to make sure ML model works
- [ ] update report
- [x] email Joe, set up time to meet (what kind of data is impactful, how to present it)
- [x] get a good understanding about rms, decibel, and relation between the two

long term, the goals are:
- write about what you found about neighborhood sounds and sound levels in the report, maybe include graph
- meet with Joe, get some ideas about next steps
- find out what this data could be used for, if different/more data needs to be collected
- find out rms-to-decibel conversion, think about how you could use your box to pick up noises based on decibels

**Comment by apzzd** [comment]
***Update:***
The laptop was used to record a file rather than the Voice Box, due to technical issues that will be solved at a later time.
